# Generated by Django 6.0.5 on 2026-07-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doacao_fk_iddoador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True, 'ordering': ['-valor_impacto'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='campanha',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='campanha',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='campanhas/fotos/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
