# Generated by Django 6.0.5 on 2026-07-06 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_options_campanha_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemCampanha',
            fields=[
                ('idimagem', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='campanhas/galeria/')),
                ('fk_idcampanha', models.ForeignKey(db_column='fk_idcampanha', on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.campanha')),
            ],
            options={
                'db_table': 'ImagemCampanha',
                'managed': True,
            },
        ),
    ]
