# Generated by Django 6.0.5 on 2026-07-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_imagemcampanha'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='subtitulo',
            field=models.TextField(default=''),
        ),
    ]
