# Generated by Django 6.0.5 on 2026-07-08 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_campanha_subtitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtualizacaoCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_atualizacao', models.DateField(auto_now_add=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='campanhas/atualizacoes/')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atualizacoes', to='core.campanha')),
            ],
            options={
                'ordering': ['-data_atualizacao'],
            },
        ),
    ]
